name: Auto close issues on Fix commits

on:
  push:
    branches:
      - '**'

permissions:
  issues: write
  contents: read

jobs:
  close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Fermer les issues liées
        uses: actions/github-script@v7
        with:
          script: |
            const commits = context.payload.commits;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            for (const commit of commits) {
              const message = commit.message;
              const regex = /fix(?:es|ed)?\s+#(\d+)/gi;
              let match;
              while ((match = regex.exec(message)) !== null) {
                const issue_number = match[1];
                await octokit.rest.issues.update({
                  owner,
                  repo,
                  issue_number,
                  state: 'closed'
                });
              }
            }
